using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class UI : MonoBehaviour
{
    [SerializeField] private Text round;
    [SerializeField] private Text grassCount;
    [SerializeField] private Text sheepCount;
    [SerializeField] private Text wolfCount;
    [SerializeField] private Text eatGrassCount;
    [SerializeField] private Text lambEatEnoughCount;
    [SerializeField] private Text sheepEatEnoughCount;
    [SerializeField] private Text wolfEatLambCount;
    [SerializeField] private Text wolfEatSheepCount;
    [SerializeField] private Text dogAttackCount;
    [SerializeField] private Text coins;

    private void Update()
    {
        round.text = "^X: " + GameManager.Instance.Round;
        grassCount.text = "a瓜W螵杭贫q: " + MapManager.Instance.grassTiles.Count;
        sheepCount.text = "a瓜Wο杭贫q: " + GameManager.Instance.sheeps.Count;
        wolfCount.text = "a瓜WT杭贫q: " + GameManager.Instance.wolves.Count;
        eatGrassCount.text = "Y奔函罅`计: " + GameManager.Instance.grassEatCount;
        lambEatEnoughCount.text = "pοY埂害讣: " + GameManager.Instance.lambEatEnoughCount;
        sheepEatEnoughCount.text = "οY埂害讣: " + GameManager.Instance.sheepEatEnoughCount;
        wolfEatLambCount.text = "TY奔pο害讣: " + GameManager.Instance.wolfEatLambCount;
        wolfEatSheepCount.text = "TY奔ο害讣: " + GameManager.Instance.wolfEatSheepCount;
        dogAttackCount.text = "ю阑T害讣: " + GameManager.Instance.dogAttackCount;
        coins.text = "鞴艏: " + GameManager.Instance.coins;
    }
}
